# Generated by Django 4.0.4 on 2022-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_examen_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='precio',
        ),
        migrations.AddField(
            model_name='examen',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Costo del examen'),
        ),
    ]
