# Generated by Django 4.0.4 on 2022-04-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_alter_respuesta_correcto_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='correcto',
            new_name='correcta',
        ),
    ]
