# Generated by Django 4.0.4 on 2022-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_remove_examen_precio_examen_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrespondido',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Costo del examen'),
        ),
    ]
