# Generated by Django 4.0.4 on 2022-04-20 02:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examen', '0003_rename_correcto_respuesta_correcta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Profile',
        ),
    ]
