# Generated by Django 4.0.4 on 2022-04-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_rename_usuario_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='pregunta_1',
        ),
        migrations.AddField(
            model_name='examen',
            name='preguntas',
            field=models.ManyToManyField(blank=True, related_name='preguntas_examen', to='examen.pregunta'),
        ),
    ]
