# Generated by Django 4.0.4 on 2022-04-27 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_examenrespondido_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='examen_respondido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examen.examenrespondido'),
            preserve_default=False,
        ),
    ]
