# Generated by Django 4.0.4 on 2022-04-20 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examen', '0005_remove_examen_pregunta_1_examen_preguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examen',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examen',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Resultado de examen'),
        ),
    ]
