# Generated by Django 4.0.4 on 2022-04-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0006_examen_intentos_examen_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6, verbose_name='Maximo puntaje'),
        ),
    ]
