# Generated by Django 4.0.4 on 2022-04-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0007_alter_preguntasrespondidas_examen_respondido'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='opciones',
            field=models.ManyToManyField(blank=True, to='examen.respuesta'),
        ),
    ]
