# Generated by Django 4.0.4 on 2022-04-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0008_preguntasrespondidas_examen_alter_respuesta_pregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrespondido',
            name='examen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examen.examen'),
            preserve_default=False,
        ),
    ]
