# Generated by Django 4.0.4 on 2022-04-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0009_examenrespondido_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrespondido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio del examen'),
        ),
        migrations.AddField(
            model_name='profile',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Presupuesto'),
        ),
    ]
