# Generated by Django 4.0.4 on 2022-04-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_plan_caracteristica1_plan_caracteristica2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planpago',
            name='description',
        ),
        migrations.RemoveField(
            model_name='planpago',
            name='price',
        ),
        migrations.RemoveField(
            model_name='planpago',
            name='title',
        ),
        migrations.AddField(
            model_name='planpago',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Cantidad pagada'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='transaction_uuid',
            field=models.CharField(default=160827, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planpago',
            name='user_uuid',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('MEDIO', 'MEDIO'), ('PRO', 'PRO'), ('BASICO', 'BASICO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='plan_type',
            field=models.CharField(choices=[('MEDIO', 'MEDIO'), ('PRO', 'PRO'), ('BASICO', 'BASICO')], max_length=25),
        ),
    ]
