# Generated by Django 4.0.4 on 2022-04-26 00:51

from django.db import migrations, models
import perfil.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_alter_plan_plan_type_alter_planpago_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=perfil.models.user_directory_path_banner, verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=perfil.models.user_directory_path_profile, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('MEDIO', 'MEDIO'), ('BASICO', 'BASICO'), ('PRO', 'PRO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='plan_type',
            field=models.CharField(choices=[('MEDIO', 'MEDIO'), ('BASICO', 'BASICO'), ('PRO', 'PRO')], max_length=25),
        ),
    ]
