# Generated by Django 4.0.4 on 2022-04-26 01:27

from django.db import migrations, models
import django_resized.forms
import perfil.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_profile_banner_profile_picture_alter_plan_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('PRO', 'PRO'), ('MEDIO', 'MEDIO'), ('BASICO', 'BASICO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='plan_type',
            field=models.CharField(choices=[('PRO', 'PRO'), ('MEDIO', 'MEDIO'), ('BASICO', 'BASICO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='JPEG', keep_meta=True, quality=75, size=[300, 300], upload_to=perfil.models.user_directory_path_profile),
            preserve_default=False,
        ),
    ]
