# Generated by Django 4.0.4 on 2022-04-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_alter_plan_plan_type_alter_planpago_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellidos'),
        ),
    ]
