# Generated by Django 4.0.4 on 2022-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Creditos del plan'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Credito adquirido'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('MEDIO', 'MEDIO'), ('PRO', 'PRO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='plan_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('MEDIO', 'MEDIO'), ('PRO', 'PRO')], max_length=25),
        ),
    ]
