# Generated by Django 4.0.4 on 2022-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_plan_credit_planpago_credit_alter_plan_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('PRO', 'PRO'), ('MEDIO', 'MEDIO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='plan_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('PRO', 'PRO'), ('MEDIO', 'MEDIO')], max_length=25),
        ),
    ]
