# Generated by Django 4.0.4 on 2022-04-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0016_alter_plan_plan_type_alter_planpago_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('MEDIO', 'MEDIO'), ('PRO', 'PRO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='plan_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('MEDIO', 'MEDIO'), ('PRO', 'PRO')], max_length=25),
        ),
    ]
