# Generated by Django 4.0.4 on 2022-04-28 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0020_alter_plan_plan_type_alter_planpago_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateapplication',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.profile'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('PRO', 'PRO'), ('MEDIO', 'MEDIO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='plan_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('PRO', 'PRO'), ('MEDIO', 'MEDIO')], max_length=25),
        ),
    ]
