# Generated by Django 4.0.4 on 2022-04-25 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0007_profile_affiliated_profile_affiliated_url_profile_ci_and_more'),
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.plan'),
        ),
        migrations.AddField(
            model_name='shortener',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
