# Generated by Django 4.0.4 on 2022-04-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_shortener_plan_shortener_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='plan',
        ),
    ]
