# Generated by Django 4.0.4 on 2022-04-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_afiliado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Afiliado',
        ),
    ]
